[package]
name = "inverse_cubic_interpolation"
version = "0.1.0"
authors = ["padraig <n/a>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
